#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PathSim Simulation
==================

Generated by PathView on 2026-03-11 15:05:24
https://view.pathsim.org

PathSim documentation: https://docs.pathsim.org
"""

# ────────────────────────────────────────────────────────────────────────────
# IMPORTS
# ────────────────────────────────────────────────────────────────────────────

import numpy as np
import matplotlib.pyplot as plt

from pathsim import Simulation, Connection
from pathsim.blocks import (
    Adder,
    Amplifier,
    Integrator,
    Scope,
    StepSource
)
from pathsim.solvers import RKBS32

# ────────────────────────────────────────────────────────────────────────────
# USER-DEFINED CODE
# ────────────────────────────────────────────────────────────────────────────

# random feedback gain
g = np.random.rand() + 1

# random step delay
tau = np.random.rand() + 2

# random initial value
x0 = np.random.rand()

# ────────────────────────────────────────────────────────────────────────────
# BLOCKS
# ────────────────────────────────────────────────────────────────────────────

# Sources
unit_step = StepSource(
    amplitude=1,
    tau=tau
)

# Dynamic
integrator = Integrator(
    initial_value=x0
)

# Algebraic
difference = Adder(
    operations="+-"
)
feedback = Amplifier(
    gain=g
)

# Recording
result = Scope()

blocks = [
    unit_step,
    integrator,
    difference,
    feedback,
    result,
]

# ────────────────────────────────────────────────────────────────────────────
# CONNECTIONS
# ────────────────────────────────────────────────────────────────────────────

conn_0 = Connection(difference[0], integrator[0])
conn_1 = Connection(integrator[0], feedback[0])
conn_2 = Connection(feedback[0], difference[1])
conn_3 = Connection(unit_step[0], difference[0])
conn_4 = Connection(integrator[0], result[1])
conn_5 = Connection(unit_step[0], result[0])

connections = [
    conn_0,
    conn_1,
    conn_2,
    conn_3,
    conn_4,
    conn_5,
]

# ────────────────────────────────────────────────────────────────────────────
# SIMULATION
# ────────────────────────────────────────────────────────────────────────────

sim = Simulation(
    blocks,
    connections,
    Solver=RKBS32,
    dt=0.01,
    dt_min=1e-16,
    dt_max=0.1,
    tolerance_lte_rel=1e-4,
    tolerance_lte_abs=1e-6,
    tolerance_fpi=1e-9,
)

# ────────────────────────────────────────────────────────────────────────────
# MAIN
# ────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':

    # Run simulation
    sim.run(duration=10)

    # Plot results
    sim.plot()
    plt.show()
